### ISSUE TITLE
Plans to release Aggregator Module? 

### ISSUE THREAD

**Issue by Butler925** [facebookresearch/Clinical-Trial-Parser#18]
I am trying to use this code to help parse criteria for clinical trials, but am learning that the cfg and ie modules currently run separately without any way to merge the outputs. Do you plan on releasing the discussed aggregator and post-processing code or is there a way I can do it on my end? Any thoughts helpful!

**Comment by salkola** [comment]
We have no plans to augment the relation extraction module in the near future.

The outputs of the CFG and IE modules tend to have little overlap, which makes their simple combination possible. For example, when the IE label is `clinical variable`, `age` or `BMI`, we would inspect whether the CFG output has a corresponding relation so that the best result can be selected.

I look forward to your contributions!
